management:
  metrics:
    export:
      prometheus:
        enabled: true
  endpoints:
    web:
      exposure:
        include: "*"
endpoints:
  prometheus:
    enabled: true
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/katazom?useSSL=false
    username: root
    password: secret